; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

; Geschwindigkeit für den Seriellen Monitor
monitor_speed = 115200

; USB-Konfiguration für das YD-Board (S3 native USB)
build_flags = 
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
    ; Falls dein Board PSRAM hat (die meisten YD-S3 haben 8MB), aktiviere dies:
   ; -D BOARD_HAS_PSRAM

; Falls du Probleme beim Upload hast, versuche den Port festzulegen
; upload_port = COMx 

; Bibliothek einbinden
lib_deps =
   https://github.com/javier-fg/arduino_rd-03d 